### ISSUE TITLE
Very Large Log Comes up, while querying a lot of Read Queries!

### ISSUE THREAD

**Issue by crossdsection** [namshi/node-mysql2-promise#8]
logs get generated around of 90 thousand lines sometime. 

Can that be configured to not show up?

**Comment by odino** [comment]
Hi @crossdsection, we dont have console logs and so on, can you share the code thats causing all those logs? Dd you try running it with `NODE_ENV=prod`?

**Comment by hossam-fares** [comment]
@crossdsection I guess you are talking about mysql2 generated logs, by default it should not be showing unless you enable debug somehow.

Any way, to make sure debug is disabled, you can add debug option to the connection config and set it to zero, like this:

```js
var db = require('mysql2-promise')();

db.configure({
    "host": "localhost",
    "user": "foo",
    "password": "bar",
    "database": "db",
    "debug": 0
});
```

I'm closing this issue and waiting for your feedback

**Comment by crossdsection** [comment]
Thanks
